#!/bin/bash

NAME=hudren/video-server
VERSION=$(echo $(head -n 1 project.clj) | sed 's/.*"\(.*\)".*/\1/')
MINOR_VERSION=$(echo $VERSION | sed 's/\([0-9]*\)\.\([0-9]*\).*/\1.\2/')

# Grab the latest android app
if [ -f "../video-client/build/outputs/apk/video-client-release.apk" ] ; then
  rsync -a ../video-client/build/outputs/apk/video-client-release.apk resources/public
fi

# Build the server app
if [ ! -f "target/video-server.jar" ]; then
  lein with-profiles prod uberjar
fi

echo "Building docker image for Videos@Home $VERSION ($MINOR_VERSION)"
docker build -t $NAME .

docker tag $NAME $NAME:$VERSION
if [[ ! $VERSION =~ .*-SNAPSHOT$ ]] && [[ $MINOR_VERSION ]]; then
    docker tag $NAME $NAME:$MINOR_VERSION
fi

echo "Publish on Docker Hub: docker push hudren/video-server"
